
event.onmemorywrite(function(a, b, c)
	print(a)
end, 0x8003be1d)
event.onmemorywrite(function(a, b, c)
	print(a)
end, 0x8003be1e)
event.onmemorywrite(function(a, b, c)
	print(a)
end, 0x8003be1f)
event.onmemorywrite(function(a, b, c)
	print(a)
end, 0x8003be20)
event.onmemorywrite(function(a, b, c)
	print(a)
end, 0x8003be21)
event.onmemorywrite(function(a, b, c)
	print(a)
end, 0x8003be22)
event.onmemorywrite(function(a, b, c)
	print(a)
end, 0x8003be23)